#!/usr/bin/env python3
"""Generate include/commons/icons/mdi.hpp from an Iconify name list.

The input JSON has the shape ``{"names": ["ab-testing", "abacus", ...]}`` (see
``data/iconify-mdi.json``). Each name becomes a ``static constexpr Icon`` member
of ``comms::MdiSet``.

Usage:
    python3 scripts/generate_mdi_icons.py data/iconify-mdi.json > include/commons/icons/mdi.hpp

The output is piped through ``clang-format`` (using the repo ``.clang-format``)
so it satisfies ``make format-check`` and regeneration is idempotent.

Name sanitization:
    * ``-`` becomes ``_``.
    * A sanitized name that collides with a C++ keyword gets a trailing ``_``
      (for the MDI set this is only ``delete``, ``export``, ``switch``).
The icon's original name (with hyphens) is preserved as the string argument.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

# C++23 keywords and alternative tokens that cannot be used as identifiers.
CPP_KEYWORDS = {
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor",
    "bool", "break", "case", "catch", "char", "char8_t", "char16_t", "char32_t",
    "class", "compl", "concept", "const", "consteval", "constexpr", "constinit",
    "const_cast", "continue", "co_await", "co_return", "co_yield", "decltype",
    "default", "delete", "do", "double", "dynamic_cast", "else", "enum",
    "explicit", "export", "extern", "false", "float", "for", "friend", "goto",
    "if", "inline", "int", "long", "mutable", "namespace", "new", "noexcept",
    "not", "not_eq", "nullptr", "operator", "or", "or_eq", "private",
    "protected", "public", "register", "reinterpret_cast", "requires", "return",
    "short", "signed", "sizeof", "static", "static_assert", "static_cast",
    "struct", "switch", "template", "this", "thread_local", "throw", "true",
    "try", "typedef", "typeid", "typename", "union", "unsigned", "using",
    "virtual", "void", "volatile", "wchar_t", "while", "xor", "xor_eq",
}


def sanitize(name: str) -> str:
    """Turn an icon name into a valid, non-keyword C++ identifier."""
    ident = name.replace("-", "_")
    if ident in CPP_KEYWORDS:
        ident += "_"
    return ident


def render(names: list[str], source: str) -> str:
    cmd = f"python3 scripts/generate_mdi_icons.py {source} > include/commons/icons/mdi.hpp"
    lines = [
        "#pragma once",
        "",
        f"// GENERATED by scripts/generate_mdi_icons.py from {source} -- do not edit.",
        f"// Regenerate with: {cmd}",
        "",
        "#include <commons/icon.hpp>",
        "",
        "namespace comms {",
        "",
        "/// The Material Design Icons set (https://pictogrammers.com/library/mdi/).",
        '/// Each member is the `mdi:<name>` icon, e.g. `comms::Icons::mdi::abacus`.',
        'struct MdiSet : IconifySet<"mdi"> {',
    ]
    for name in names:
        ident = sanitize(name)
        if ident != name.replace("-", "_"):
            # Keyword clash: the trailing `_` is intentional and cannot be
            # "fixed", so silence the naming check for this one member.
            lines.append(
                f"    // NOLINTNEXTLINE(readability-identifier-naming): "
                f"'{name}' is a C++ keyword"
            )
        lines.append(f'    static constexpr Icon {ident} = Icon::from(set, "{name}");')
    lines += [
        "};",
        "",
        "}  // namespace comms",
        "",
    ]
    return "\n".join(lines)


def clang_format(text: str, repo_root: Path) -> str:
    try:
        result = subprocess.run(
            ["clang-format", "--style=file",
             "--assume-filename=include/commons/icons/mdi.hpp"],
            input=text,
            capture_output=True,
            text=True,
            cwd=repo_root,
            check=True,
        )
    except FileNotFoundError:
        sys.exit("error: clang-format not found; it is required for idempotent output")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"error: clang-format failed: {exc.stderr}")
    return result.stdout


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: generate_mdi_icons.py <names.json>")
    source = sys.argv[1]
    data = json.loads(Path(source).read_text())
    names = data["names"]
    repo_root = Path(__file__).resolve().parent.parent
    sys.stdout.write(clang_format(render(names, source), repo_root))


if __name__ == "__main__":
    main()
